### PR TITLE
Add undefined check before rendering a procedure date string

### PR DESCRIPTION
**Pull request by Kapin**
Weird race condition is causing a console error due to the last modified
date not being set by the server immediately. This fixes that.

### CODE REVIEW

**Comment by Trinovantes** [comment]
When it eventually gets set, does the UI get updated?

**Comment by Kapin** [comment]
That will never happen as we transition to the next page. I have no found a way to test it.

**Comment by Trinovantes** [comment]
Why does this old UI get updated if we're supposed to transition?

**Comment by Kapin** [comment]
@Trinovantes it's a race condition with ember. The model is created before the transition occurs. This is a much simpler fix than forcibly preventing a refresh from ember.

**Comment by Trinovantes** [comment]
Can you ask the developers on IRC to see if this the only solution or if there's another paradigm that we're not aware of?

**Comment by Trinovantes** [comment]
Stopped development with Ember

**Pull request closed without merging**
