### PR TITLE
Skeleton web app for Backbone frontend

### PR DESCRIPTION
**Pull request by Trinovantes**
This is an empty skeleton app for a Backbone app using Gulp and
Browserify (Coffeeify). We can use both CoffeeScript/JavaScript if we
need to.

Make sure you run `bower install` and `npm install` in the src-backbone
directory to install all the dependencies. Also need to install these
node packages globally:

    npm install -g bower
    npm install -g gulp
    npm install -g coffee-script

Then you can simply run `gulp` to serve up a static page at
localhost:8080.

Note that bower components need to be stictly JS packages. I haven't
configured gulp to pull out CSS/fonts found in some packages such as
Bootstrap.

### CODE REVIEW

**Comment by Trinovantes** [comment]
The live reload requires a Firefox/Chrome extension https://chrome.google.com/webstore/detail/livereload/jnihajbhpnppcggbcgedagnkighmdlei

**Comment by Ommy** [comment]
Overall looks fine, only 1 question. Going forward are we mainly going to be writing in Coffeescript?

Other then that, +1

**Comment by Trinovantes** [comment]
yea I'm assuming we're going forward with coffeescript

**Comment by Ommy** [comment]
Ok sounds good. I was mainly asking because of the JSHint package being added while we're using Coffee.

**Comment by ConnorCimowsky** [comment]
LGTM. Did you use a setup guide, or just figured it out as you went along?

**Comment by Trinovantes** [comment]
Had to glue several tutorials together. We're using such a weird combination of browserify, gulp, and coffeescript.

**Pull request merged**
