### PR TITLE
Conditional Enhancements

### PR DESCRIPTION
**Pull request by Trinovantes**
This will contain all the missing enhancements for conditional logic UI. I would suggest you read each commit individually (skip the second commit since that's just reorganization).

- [x] Highlight pages in sidebar containing operand elements
- [ ] Show preview of condition in page list (#331)
- [x] Auto-complete for elements (#332)
- [x] Auto-complete for value (if possible) (#333)
- [x] First page should have no options to create conditional logic
- [x] If page is moved to first page, condition should be removed
- [x] If page P is moved above a page that contains elements that P depends on, condition should be removed

### CODE REVIEW

**Comment by Kapin** [comment]
@Trinovantes can we review/merge what is in here so far?

**Comment by Trinovantes** [comment]
Sure?

**Comment by Trinovantes** [comment]
I'm going to cherry pick the choices-related commits to your branch and fix the multi-answers at the same time. This PR will only contain changes related to conditionals

**Comment by connorcimowsky** [comment]
As per Josh's suggestion, :+1:

**Comment by connorcimowsky** [comment]
BTW, my work is based on this branch — it would be great if we could merge this soon

**Comment by Kapin** [comment]
This is fine to me. Merge please before doing any more work.

**Pull request merged**
