### PR TITLE
Setup Grunt

### PR DESCRIPTION
**Pull request by Trinovantes**
- Now automatically compile bootstrap.less when you run 'grunt' in root
  directory. We will still use Django's compressor when generating files for
  production since it automatically rewrites the URL in our templates.

### CODE REVIEW

**Comment by Trinovantes** [comment]
This is also a prerequisite for automatically generating Ember templates into a single file (to be implemented in the future)

**Comment by Kapin** [comment]
Update the mac install script and it gets a :+1:

**Comment by Trinovantes** [comment]
I don't have a mac to test `npm install -g grunt-cli`

**Comment by ConnorCimowsky** [comment]
Can confirm that it works on 10.10.2. LGTM!

**Pull request merged**
