### PR TITLE
Fixed addition of pages at specific indexes

### LINKED ISSUE #182: Adding a new page should push the pages below it down and increment their indices
Currently it gets assigned the current index where the `+` was clicked, but doesn't update the display indices of the rest of the pages below that `+`. We should increment all the other pages and send a bulk update.

### PR DESCRIPTION
**Pull request by Ommy**
This is when we want to create a new page in between two pages.
Before it wasn't updating the display indices of the other pages.

Resolves #182

### CODE REVIEW

**Comment by Kapin** [comment]
LGTM

**Comment by Trinovantes** [comment]
Is this handled on the server too?

**Comment by ConnorCimowsky** [comment]
Should we be updating the records locally before sending the request? I think right now we only do this when we receive the response and push the records into the store.

**Comment by Trinovantes** [comment]
Yea I'd rather let the server notify Ember that some page changed on the backend than to let Ember guess what's happening on the backend

**Comment by ConnorCimowsky** [comment]
Let's talk about this in person tomorrow :+1:

**Comment by ConnorCimowsky** [comment]
Re: offline discussion, I think we'll keep it as-is?

**Comment by Ommy** [comment]
"+1" - @Trinovantes

**Comment by ConnorCimowsky** [comment]
+1

**Pull request merged**
