### PR TITLE
Explicitly make all foreign key deletes cascade

### PR DESCRIPTION
**Pull request by Kapin**
It defaults to this, but better for my piece of mind and it becomes mandatory to do this in Django 2.0

### CODE REVIEW

**Comment by Ommy** [comment]
lgtm for the most part. Can we add some tests for this functionality?

**Comment by Kapin** [comment]
Yes

**Comment by Trinovantes** [comment]
should also remove references of elements from conditions

**Comment by Kapin** [comment]
@Trinovantes that is much more complicated as there isn't really a way of easily determining whether an element has references to conditions right now.

**Pull request merged**
