### PR TITLE
Show spinner when making AJAX requests

### LINKED ISSUE #189: Add loading spinners for all network-bound operations

### PR DESCRIPTION
**Pull request by Trinovantes**
Closes #189

### CODE REVIEW

**Comment by Ommy** [comment]
+1

**Comment by Kapin** [comment]
:shipit:

**Comment by ConnorCimowsky** [comment]
y u no [spin.js](http://fgnass.github.io/spin.js/)

LGTM either way

**Comment by Trinovantes** [comment]
no more dependencies >:(

**Pull request merged**
