### PR TITLE
Set up deployment of Ember application

### PR DESCRIPTION
**Pull request by ConnorCimowsky**

### CODE REVIEW

**Comment by ConnorCimowsky** [comment]
Will get to [this](https://github.com/SanaMobile/sana.protocol_builder/issues/100) when I have a chance.

**Comment by Kapin** [comment]
I think it's ok?

**Comment by ConnorCimowsky** [comment]
a ringing endorsement

**Comment by Kapin** [comment]
:bell:

**Comment by Trinovantes** [comment]
+1

**Pull request merged**
