### PR TITLE
Add user registration endpoint

### PR DESCRIPTION
**Pull request by Trinovantes**
Example usage (with HTTPie):
```
http -v --form POST localhost:8000/auth/signup \
username=test password1=test password2=test email=test0@test.com accept_tos=True
```

### CODE REVIEW

**Comment by ConnorCimowsky** [comment]
:+1:

**Comment by Trinovantes** [comment]
Note that the request/response for `/auth/signup` looks like this:
```
POST /auth/signup HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate, compress
Content-Length: 89
Content-Type: application/x-www-form-urlencoded; charset=utf-8
Host: localhost:8000
User-Agent: HTTPie/0.8.0

username=test15&password1=test15&password2=test15&email=test15%40test.com&accept_tos=True

HTTP/1.0 200 OK
Content-Type: application/json
Date: Mon, 25 May 2015 03:47:38 GMT
Server: WSGIServer/0.1 Python/2.7.6
X-Frame-Options: SAMEORIGIN

{
    "errors": {}, 
    "success": true, 
    "token": "b602b11c530192b8995867316b56299587a4e3dd"
}
```

Whereas the request/response for `/auth/login` looks like this (due to directly calling the REST framework):
```
POST /auth/login HTTP/1.1
Accept: application/json
Accept-Encoding: gzip, deflate, compress
Content-Length: 44
Content-Type: application/json; charset=utf-8
Host: localhost:8000
User-Agent: HTTPie/0.8.0

{
    "password": "test15", 
    "username": "test15"
}

HTTP/1.0 200 OK
Allow: POST, OPTIONS
Content-Type: application/json
Date: Mon, 25 May 2015 03:49:12 GMT
Server: WSGIServer/0.1 Python/2.7.6
X-Frame-Options: SAMEORIGIN

{
    "token": "b602b11c530192b8995867316b56299587a4e3dd"
}
```

I'll make the login consistent in another commit.

**Comment by ConnorCimowsky** [comment]
@Kapin pls

**Comment by ConnorCimowsky** [comment]
@Kapin please review this after I merge. I needed the endpoint to test the frontend!

**Pull request merged**
