### PR TITLE
Fix environment variables

### PR DESCRIPTION
**Pull request by ConnorCimowsky**

### CODE REVIEW

**Comment by Kapin** [comment]
Can you make the generate env variable a generate URL and change the value in the ajax call? It's probably a little less silly and error prone.

**Comment by ConnorCimowsky** [comment]
Yup agreed

**Comment by ConnorCimowsky** [comment]
@Kapin err, the model's id has to be placed in the middle of the URL 😕

**Comment by Kapin** [comment]
@ConnorCimowsky oh poop... yeah, don't change that then...

**Comment by Trinovantes** [comment]
+1

**Pull request merged**
