### PR TITLE
Transition to procedures if logged in

### LINKED ISSUE #179: Going to the website should redirect to /procedures/ if the user is logged in.
Currently it goes to a blank screen. The default view should be the procedure view.

screen shot 2015-07-08 at 3 10 42 pm

### PR DESCRIPTION
**Pull request by ConnorCimowsky**
Resolves #179

### CODE REVIEW

**Comment by Ommy** [comment]
Does this guarantee that the user is logged in before transitioning? Like if we get to that `beforeModel`, we know the user is logged in?

**Comment by ConnorCimowsky** [comment]
No, but the procedures route will redirect to the login page if they're not logged in. Is that the behaviour we want?

**Comment by Ommy** [comment]
Yeah that works, +1

**Comment by Kapin** [comment]
:boom:

**Pull request merged**
