### PR TITLE
Make create/update in serializer for conditional logic atomic

### LINKED ISSUE #318: Race condition when trying to update criteria
If I try to update a criteria in 2 quick requests, there's a race condition that causes the first response to return 2 nodes and second response to return 0 nodes.

Request 1:
```
{
   "page":28,
   "id":60,
   "last_modified":"2016-02-21T23:26:14.286201Z",
   "created":"2016-02-21T23:26:14.252864Z",
   "conditions":[
      {
         "criteria_element":null,
         "node_type":"EQUALS",
         "value":"asd"
      }
   ]
}
```

Request 2:
```
{
   "page":28,
   "id":60,
   "last_modified":"2016-02-21T23:26:14.286201Z",
   "created":"2016-02-21T23:26:14.252864Z",
   "conditions":[
      {
         "criteria_element":null,
         "node_type":"EQUALS",
         "value":"asdf"
      }
   ]
}
```

Response 1:
```
{
   "id":60,
   "page":28,
   "last_modified":"2016-02-21T23:26:17.789627Z",
   "created":"2016-02-21T23:26:14.252864Z",
   "conditions":[
      {
         "id":172,
         "parent":null,
         "criteria_element":null,
         "node_type":"EQUALS",
         "value":"asd",
         "last_modified":"2016-02-21T23:26:17.778803Z",
         "created":"2016-02-21T23:26:17.778831Z",
         "show_if":60,
         "children":[

         ]
      },
      {
         "id":173,
         "parent":null,
         "criteria_element":null,
         "node_type":"EQUALS",
         "value":"asdf",
         "last_modified":"2016-02-21T23:26:17.779719Z",
         "created":"2016-02-21T23:26:17.779743Z",
         "show_if":60,
         "children":[

         ]
      }
   ]
}
```

Response 2:
```
{
   "id":60,
   "page":28,
   "last_modified":"2016-02-21T23:26:17.753356Z",
   "created":"2016-02-21T23:26:14.252864Z",
   "conditions":[

   ]
}
```

### PR DESCRIPTION
**Pull request by Kapin**
May close #318

### CODE REVIEW

**Comment by Ommy** [comment]
lgtm

**Comment by connorcimowsky** [comment]
assuming there's a good reason to remove the `try`-`except` block, lgtm

**Comment by Trinovantes** [comment]
Not sure if this resolves the bug. Still occasionally (less often than before) getting the duplicate ShowIfs

**Comment by Kapin** [comment]
@Trinovantes I have no other ways to add concurrency control without versioning and throwing throttling errors to my knowledge. How often are these requests being sent?

**Pull request closed without merging**
