### PR TITLE
Upgrade requirements

### PR DESCRIPTION
**Pull request by Trinovantes**
This change allows the transition to 1.9 if we want to upgrade now or later.

### CODE REVIEW

**Comment by Trinovantes** [comment]
This works so may as well merge it in now ¯\_(ツ)_/¯

**Comment by Kapin** [comment]
Can you squash this into one commit in case we run into other problems

**Comment by Trinovantes** [comment]
The only thing that we need to undo (if there's any problems) is the actual bump. The first commit is compatible with 1.8.x

**Comment by Kapin** [comment]
lgtm then

**Pull request merged**
