### PR TITLE
Add factory boy to make tests look less gross

### LINKED ISSUE #114: Create Factories for easily creating database model objects for tests

### PR DESCRIPTION
**Pull request by Kapin**
Factory boy auto-generates things and makes tests less boilerplatey.

Closes #114

### CODE REVIEW

**Comment by Trinovantes** [comment]
+1

**Comment by Ommy** [comment]
Can we pass in custom arguments into the factory constructor? Like specifying a certain name for an object?

**Comment by ConnorCimowsky** [comment]
Nice! LGTM

**Comment by Kapin** [comment]
@Ommy yes

**Pull request merged**
