### PR TITLE
Fix infinite 403 errors(!!!)

### LINKED ISSUE #191: Ember gets into an infinite POST /logout loop when you try to login with invalid credentials
When you are on the login page and click `Log in` with invalid credentials then the application gets stuck in an infinite loop sending `POST` to `/auth/logout`. Each `POST` ends up being a `401` and floods the console.

## To Reproduce

1. Go to the login page
2. Leave the login fields blank, or provide invalid credentials
3. Click Login

### PR DESCRIPTION
**Pull request by ConnorCimowsky**
Resolves #191

ro34jp-byskc

### CODE REVIEW

**Comment by Ommy** [comment]
+1

**Comment by ConnorCimowsky** [comment]
d91

**Comment by Trinovantes** [comment]
+1

**Comment by Kapin** [comment]
:+1:

**Pull request merged**
